export enum ELinks {
    HOME = '/',
    DASHBOARD = '/dashboard',
    SIGN_IN = '/sign-in',
    SIGN_UP = '/sign-up',
    RECOVERY = '/recovery-password',
    RESET_PASSWORD = '/reset-password',
    CALENDAR = '/calendar',
    CATEGORIES = '/categories',
    OFFER = '/offer',
    WORK_ORDERS = '/work-orders',
    SETTINGS = '/settings',
    USERS_LIST = '/users-list',
    GROUPS_LIST = '/groups-list',
    BOXES_LIST = '/boxes-list',
    INFORMATION_PAGES = '/information-pages',
    INFORMATION_PAGE_CREATE = '/information-pages/create',
    INFORMATION_PAGE_EDIT = '/information-pages/:id/edit',
    CONTENT_PAGE_PUBLIC = '/p/:shopSlug/:slug',
    SALES_LIST = '/sales',
    SALES_ORDER_LIST = `/sales/:id`,
    SALES_ORDER_CREATE = `/sales/create`,
    MONEY_LIST = '/my-wallet',
    MONEY_DEPOSIT = '/my-wallet/deposit',
    MONEY_WITHDRAW = '/my-wallet/withdraw',
    MONEY_TRANSFERS_LIST = '/money/transfers',

    STOCK_PROVIDER_LIST = '/stock/provider',
    STOCK_RECEIPTS_LIST = '/stock/receipts',
    STOCK_ADJUSTMENT_LIST = '/stock/adjustment',

    /** Маркетинг / прочие витринные разделы */
    FINANCIAL_REPORT = '/financial-report',
    RECORD_FUND = '/record-fund',
    /** Хранение продуктов — отдельная страница, не список товаров склада. */
    PRODUCT_HOLD = '/product/hold',
    PRODUCT_RETURN_REQUEST = '/product/return-request',
    PRODUCT_OVERVIEW = '/product/overview',
    PRODUCT_WAREHOUSE = '/product/warehouse',
    PRODUCT_IMPORT = '/product/import',
    BUSINESS_LEAGUE = '/business-league',
    MARKETING_SHOP_EXPRESS = '/marketing/shop-express',
    MARKETING_PURCHASE_HISTORY = '/marketing/purchase-history',
    MARKETING_SELLER_LEVEL = '/marketing/seller-level',

    NOT_FOUND = '*',
}
